apiVersion: v1
kind: Service
metadata:
  name: herd-controller
  namespace: herd-system
  labels:
    app.kubernetes.io/name: herd
    app.kubernetes.io/component: controller
spec:
  selector:
    app.kubernetes.io/name: herd
    app.kubernetes.io/component: controller
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  type: ClusterIP
