# Example Secrets containing sensitive Helm values
---
apiVersion: v1
kind: Secret
metadata:
  name: jupyterhub-secrets
  namespace: default
type: Opaque
stringData:
  auth-config.yaml: |
    # JupyterHub authentication configuration
    hub:
      config:
        GitHubOAuthenticator:
          client_id: "your-github-client-id"
          client_secret: "your-github-client-secret"
          oauth_callback_url: "https://jupyter.example.com/hub/oauth-callback"
        
        JupyterHub:
          authenticator_class: "oauthenticator.GitHubOAuthenticator"
    
    proxy:
      secretToken: "super-secret-proxy-token-change-me-in-production"
