apiVersion: herd.suse.com/v1
kind: Stack
metadata:
  name: working-test
  namespace: default
  labels:
    test: reliable-chart
spec:
  env: dev
  targets:
    clusterIds:
      - c-qkm2t  # Your working downstream cluster
  charts:
    - name: nginx
      repo: https://charts.bitnami.com/bitnami
      version: "18.1.9"
      namespace: test-working
      releaseName: working-nginx
      values:
        inline:
          # Minimal nginx that definitely creates pods
          replicaCount: 1
          image:
            repository: nginx
            tag: "1.25"
            pullPolicy: IfNotPresent
          service:
            type: ClusterIP
            port: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          # Disable complex features
          ingress:
            enabled: false
          metrics:
            enabled: false
          autoscaling:
            enabled: false
      
      wait: true
      timeout: "3m"
      createNamespace: true
