apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "herd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "herd.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      {{- include "herd.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        {{- include "herd.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: controller
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "herd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: controller
        image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
        imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
        env:
        - name: RANCHER_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "herd.fullname" . }}-config
              key: rancher-url
        - name: RANCHER_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "herd.fullname" . }}-config
              key: rancher-token
        - name: RANCHER_VERIFY_SSL
          value: {{ .Values.rancher.verifySSL | quote }}
        - name: RANCHER_TIMEOUT
          value: {{ .Values.rancher.timeout | quote }}
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          {{- toYaml .Values.controller.resources | nindent 10 }}
        {{- if .Values.healthCheck.enabled }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: {{ .Values.healthCheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthCheck.periodSeconds }}
          timeoutSeconds: {{ .Values.healthCheck.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        {{- end }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 30
