{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "herd.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "herd.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "herd.fullname" . }}
  labels:
    {{- include "herd.labels" . | nindent 4 }}
rules:
# Stack CRD management
- apiGroups: ["herd.suse.com"]
  resources: ["stacks"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["herd.suse.com"]
  resources: ["stacks/status"]
  verbs: ["get", "update", "patch"]

# ConfigMap and Secret access for values
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]

# Fleet Bundle management
- apiGroups: ["fleet.cattle.io"]
  resources: ["bundles", "clusters", "gitrepos"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Events for logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

# Kopf framework requirements
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "watch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "herd.fullname" . }}
  labels:
    {{- include "herd.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "herd.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "herd.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
