apiVersion: v1
kind: Secret
metadata:
  name: {{ include "herd.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "herd.labels" . | nindent 4 }}
type: Opaque
stringData:
  rancher-url: {{ .Values.rancher.url | quote }}
  rancher-token: {{ .Values.rancher.token | quote }}
